- name: Get rustup script
  ansible.builtin.get_url:
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    url: https://sh.rustup.rs

- name: Install rustup
  ansible.builtin.shell:
    cmd: /tmp/sh.rustup.rs -y

- name: Remove rustup script
  ansible.builtin.file:
    dest: /tmp/sh.rustup.rs
    state: absent

- name: Get codium.rpm
  ansible.builtin.shell:
    cmd: curl https://api.github.com/repos/VSCodium/vscodium/releases/latest | grep -iE '"browser_download_url\":.*x86_64.rpm"' | awk '{print $2}' | sed s/\"//g | xargs wget -O /tmp/codium.rpm
  register: down_codium
  when: codium

- name: Install codium.rpm
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: /tmp/codium.rpm
    state: present
  become: true
  when: down_codium is not skipped

- name: Remove codium.rpm
  ansible.builtin.file:
    path: /tmp/codium.rmp
    state: absent
  when: down_codium is not skipped
