- name: Get rustup
  ansible.builtin.get_url:
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    url: https://sh.rustup.rs

- name: Install rustup
  ansible.builtin.shell:
    cmd: /tmp/sh.rustup.rs -y

- name: Remove rustup script
  ansible.builtin.file:
    dest: /tmp/sh.rustup.rs
    state: absent
