# Rust
- name: Is Rustup intalled
  ansible.builtin.stat:
    path: "/home/{{ ansible_user_id }}/.cargo/bin/rustup"
  register: rust_result
  when: rust

# If rustup installed
- name: Rustup update
  ansible.builtin.command:
    cmd: "/home/{{ ansible_user_id }}/.cargo/bin/rustup update"
  changed_when: false
  when:
    - rust_result.stat is defined
    - rust_result.stat.exists

# Else
- name: Get rustup script
  ansible.builtin.get_url:
    dest: /tmp/sh.rustup.rs
    mode: '0700'
    url: https://sh.rustup.rs
  register: down_rust
  when:
    - rust_result.stat is defined
    - not rust_result.stat.exists

- name: Install rustup
  ansible.builtin.command:
    cmd: /tmp/sh.rustup.rs -y
  when: down_rust is not skipped
  changed_when: false

- name: Remove rustup script
  ansible.builtin.file:
    dest: /tmp/sh.rustup.rs
    state: absent
  when: down_rust is not skipped

# Go
- name: Get go
  ansible.builtin.get_url:
    dest: /tmp/go.tar.gz
    mode: '0600'
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
  register: down_go
  when: go

- name: Remove old go folder
  ansible.builtin.file:
    dest: /usr/local/go
    state: absent
  when: down_go is not skipped
  become: true

- name: Extract new go folder
  ansible.builtin.unarchive:
    dest: /usr/local
    src: /tmp/go.tar.gz
  when: down_go is not skipped
  become: true

- name: Remove go tar
  ansible.builtin.file:
    dest: /tmp/go.tar.gz
    state: absent
  when: down_go is not skipped

# Ocaml
- name: Is Opam intalled
  ansible.builtin.stat:
    path: "/usr/local/bin/opam"
  register: opam_result
  when: ocaml

# If opam installed
- name: Opam update, upgrade
  ansible.builtin.shell:
    cmd: "/usr/local/bin/opam update -y && /usr/local/bin/opam upgrade -y"
  changed_when: false
  when:
    - opam_result.stat is defined
    - opam_result.stat.exists

# Else
# Interactive script - can't execute here, put in home dir for manual use
- name: Get opam
  ansible.builtin.get_url:
    dest: "/home/{{ ansible_user_id }}/install_opam.sh"
    mode: '0700'
    url: https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh
  register: down_ocaml
  when:
    - opam_result.stat is defined
    - not opam_result.stat.exists
