- name: Get rustup
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install rustup
  ansible.builtin.shell:
    cmd: /tmp/sh.rustup.rs -y
  become: true

- name: Remove rustup
  ansible.builtin.file:
    dest: /tmp/sh.rustup.rs
    state: absent
