# Rust
- name: Get rustup script
  ansible.builtin.get_url:
    dest: /tmp/sh.rustup.rs
    mode: '0700'
    url: https://sh.rustup.rs
  register: down_rust
  when: rust

- name: Install rustup
  ansible.builtin.shell:
    cmd: /tmp/sh.rustup.rs -y
  when: down_rust is not skipped

- name: Remove rustup script
  ansible.builtin.file:
    dest: /tmp/sh.rustup.rs
    state: absent
  when: down_rust is not skipped

# Go
- name: Get go
  ansible.builtin.get_url:
    dest: /tmp/go.tar.gz
    mode: '0600'
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
  register: down_go
  when: go

- name: Remove old go folder
  ansible.builtin.file:
    dest: /usr/local/go
    state: absent
  when: down_go is not skipped
  become: true

- name: Extract new go folder
  ansible.builtin.unarchive:
    dest: /usr/local
    src: /tmp/go.tar.gz
  when: down_go is not skipped
  become: true

- name: Remove go tar
  ansible.builtin.file:
    dest: /tmp/go.tar.gz
    state: absent
  when: down_go is not skipped
