- name: Download calibre script
  ansible.builtin.get_url:
    dest: /tmp/calibre.sh
    mode: '0755'
    url: https://download.calibre-ebook.com/linux-installer.sh
  register: down_calibre
  when: calibre

- name: Install calibre
  ansible.builtin.command:
    cmd: /tmp/calibre.sh
  when: down_calibre is not skipped
  changed_when: false
  become: true

- name: Delete calibre script
  ansible.builtin.file:
    path: /tmp/calibre.sh
    state: absent
  when: down_calibre is not skipped

- name: Clone keyd
  ansible.builtin.git:
    repo: https://github.com/rvaiya/keyd
    dest: "/home/{{ ansible_user_id }}/keyd"
    version: "{{ keyd_v }}"
  register: down_keyd
  when: keyd

- name: Make keyd
  community.general.make:
    chdir: "/home/{{ ansible_user_id }}/keyd"
  when: down_keyd is not skipped

- name: Make install keyd
  community.general.make:
    chdir: "/home/{{ ansible_user_id }}/keyd"
    target: install
  become: true
  when: down_keyd is not skipped
  changed_when: false

- name: Enable keyd
  ansible.builtin.systemd:
    enabled: true
    name: keyd
  become: true
  when: down_keyd is not skipped

- name: Remove keyd dir
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/keyd"
    state: absent
  when: down_keyd is not skipped
