# Utils
- name: Util install
  ansible.builtin.package:
    name:
      - fzf
      - neovim
      - yt-dlp
      - zsh
    state: present
  become: true

- name: Install groups
  ansible.builtin.include_tasks:
    file: install-group.yml
  with_items:
    - "'C Development Tools and Libraries'"
    - "'Development Libraries'"
    - "'Development Tools'"
    - "'Virtualization'"

# Development
- name: DNF dev install
  ansible.builtin.package:
    name:
      - freetype-devel
      - fontconfig-devel
      - libxcb-devel
      - libxkbcommon-devel
    state: present
  become: true

- name: Install custom development
  ansible.builtin.include_tasks:
    file: dev-custom.yml

- name: Cargo install
  ansible.builtin.include_tasks:
    file: install-cargo.yml
  with_items:
    - alacritty
    - broot
    - exa
    - fd-find
    - ripgrep
    - tealdeer
    - zoxide

# General programs
- name: General install
  ansible.builtin.package:
    name:
      - celluloid
      - chromium
      - keepassxc
      - texmaker
  become: true

- name: Flatpak install
  ansible.builtin.flatpak:
    name:
      - com.bitwarden.desktop
    state: present
  become: true
