- name: Install utils
  ansible.builtin.include_tasks:
    file: install.yml
  with_items:
    - fzf
    - neovim
    - yt-dlp
    - zsh
  become: true

- name: Install package development
  ansible.builtin.include_tasks:
    file: install.yml
  with_items:
    - python
  become: true

- name: Install custom development
  ansible.builtin.include_tasks:
    file: dev-custom.yml

- name: Install general software
  ansible.builtin.include_tasks:
    file: install.yml
  with_items:
    - chromium
    - keepassxc
    - texmaker
  become: true

- name: Install software, flatpak
  ansible.builtin.include_tasks:
    file: install-flatpak.yml
  with_items:
    - com.bitwarden.desktop
    - com.brave.Browser
    - io.github.celluloid_player.celluloid
  become: true

- name: Install software, cargo
  ansible.builtin.include_tasks:
    file: install-cargo.yml
  with_items:
    - alacritty
    - broot
    - exa
    - fd-find
    - ripgrep
    - tealdeer
    - zoxide
  become: true
