# Utils
- name: Util install
  ansible.builtin.package:
    name:
      - fish
      - neovim
    state: present
  become: true

- name: Ensure fish conf dir
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.config/fish/conf.d"
    state: directory
    mode: "0755"

# Development
- name: DNF dev install
  ansible.builtin.package:
    name:
      - cmake
      - fontconfig-devel
      - freetype-devel
      - g++
      - gcc
      - libxcb-devel
      - libxkbcommon-devel
      - patch
      - perl-FindBin
    state: present
  become: true

- name: Install custom development
  ansible.builtin.include_tasks:
    file: dev-custom.yml

# Language managers
- name: Cargo install
  community.general.cargo:
    name:
      - alacritty
      - exa
      - ripgrep
      - tealdeer
      - zellij
      - zoxide
    state: latest

- name: Pip update
  ansible.builtin.pip:
    name:
      - neovim
    state: forcereinstall

- name: Go install
  ansible.builtin.command:
    cmd: "/usr/local/go/bin/go install {{ item }}"
  changed_when: false
  with_items:
    - github.com/jesseduffield/lazygit@latest

- name: Opam install
  ansible.builtin.command:
    cmd: "opam install {{ item }} -y"
  changed_when: false
  with_items:
    - ocamlformat
    - ocaml-lsp-server
    - odoc
    - utop

# General programs
- name: General install
  ansible.builtin.package:
    name:
      - celluloid
      - chromium
      - keepassxc
      - libreoffice
      - tor
    state: present
  become: true

- name: Flatpak install
  community.general.flatpak:
    name:
      - com.bitwarden.desktop
      - net.mullvad.MullvadBrowser
    state: present
  become: true

- name: Install custom general
  ansible.builtin.include_tasks:
    file: gen-custom.yml
