# Utils
- name: Util install
  ansible.builtin.package:
    name:
      - fish
      - neovim
      - openssl
      - pip
    state: present
  become: true

- name: Ensure fish conf dir
  ansible.builtin.file:
    mode: "0755"
    path: "/home/{{ ansible_user_id }}/.config/fish/conf.d"
    state: directory

# Development
- name: DNF dev install
  ansible.builtin.package:
    name:
      - cmake
      - fontconfig-devel
      - freetype-devel
      - g++
      - gcc
      - libxcb-devel
      - libxkbcommon-devel
      - lld
      - patch
      - perl-File-Compare
      - perl-File-Copy
      - perl-FindBin
      - perl-IPC-Cmd
    state: present
  become: true

- name: Install custom development
  ansible.builtin.include_tasks:
    file: dev-custom.yml

# Language managers
- name: Cargo install
  community.general.cargo:
    executable: "/home/{{ ansible_user_id }}/.cargo/bin/cargo"
    name:
      - alacritty
      - bat
      - exa
      - ripgrep
      - tealdeer
      - zellij
      - zoxide
    state: latest

- name: Pip install
  ansible.builtin.pip:
    name:
      - neovim
      - psutil
    extra_args: --upgrade

- name: Go install
  ansible.builtin.command:
    cmd: "/usr/local/go/bin/go install {{ item }}"
  # TODO: Read stdout to see if any updates happened
  changed_when: false
  with_items:
    - github.com/jesseduffield/lazygit@latest

- name: Is Opam installed
  ansible.builtin.stat:
    path: "/usr/local/bin/opam"
  register: opam_result

- name: Opam install
  ansible.builtin.command:
    cmd: "opam install {{ item }} -y"
  # TODO: Read stdout to see if any updates happened
  changed_when: false
  when: opam_result.stat.exists
  with_items:
    - ocamlformat
    - ocaml-lsp-server
    - odoc
    - utop

# General programs
- name: General install
  ansible.builtin.package:
    name:
      - celluloid
      - chromium
      - keepassxc
      - libreoffice
      - tor
    state: present
  become: true

- name: Flatpak install
  community.general.flatpak:
    name:
      - com.bitwarden.desktop
      - com.brave.Browser
      - com.spotify.Client
      - net.mullvad.MullvadBrowser
    state: present
  become: true

- name: Install custom general
  ansible.builtin.include_tasks:
    file: gen-custom.yml
