# Utils
- name: Util install
  ansible.builtin.package:
    name:
      - deja-dup
      - fzf
      - gnome-tweaks
      - neovim
      - zsh
    state: present
  become: true

- name: Group install
  ansible.builtin.shell:
    cmd: dnf group install --with-optional {{ item }} -y
  with_items:
    - "'C Development Tools and Libraries'"
    - "'Development Libraries'"
    - "'Virtualization'"
  become: true

# Development
- name: DNF dev install
  ansible.builtin.package:
    name:
      - fontconfig-devel
      - freetype-devel
      - golang
      - java-devel
      - java-openjdk
      - libxcb-devel
      - libxkbcommon-devel
    state: present
  become: true

- name: Install custom development
  ansible.builtin.include_tasks:
    file: dev-custom.yml

# Language managers
- name: Cargo install
  ansible.builtin.shell:
    cmd: "~/.cargo/bin/cargo install {{ item }} --locked"
  with_items:
    - alacritty
    - broot
    - exa
    - fd-find
    - ripgrep
    - tealdeer
    - zoxide

- name: Pip install
  ansible.builtin.shell:
    cmd: "pip install -U {{ item }}"
  with_items:
    - neovim
    - psutil

# General programs
- name: General install
  ansible.builtin.package:
    name:
      - celluloid
      - chromium
      - keepassxc
      - libreoffice
      - texmaker
      - yt-dlp
  become: true

- name: Flatpak install
  ansible.builtin.flatpak:
    name:
      - com.bitwarden.desktop
      - com.brave.Browser
    state: present
  become: true

- name: Install custom general
  ansible.builtin.include_tasks:
    file: gen-custom.yml
