- name: DNF autoremove
  ansible.builtin.dnf:
    autoremove: true
  become: true

- name: Flatpak autoremove
  ansible.builtin.command:
    cmd: flatpak remove --unused --noninteractive --assumeyes
  changed_when: false

- name: Reboot
  ansible.builtin.command:
    cmd: shutdown -r +1 "Rebooting in 60 seconds"
  when: reboot
  changed_when: false
  become: true

- name: Shutdown
  ansible.builtin.command:
    cmd: shutdown +1 "Shutting down in 60 seconds"
  when: shutdown
  changed_when: false
  become: true
