- name: DNF autoremove
  ansible.builtin.dnf:
    autoremove: true
  become: true

- name: Flatpak autoremove
  ansible.builtin.command:
    cmd: flatpak remove --unused --noninteractive --assumeyes
  changed_when: false

- name: Reboot
  ansible.builtin.reboot:
    msg: "Rebooting machine in 60 seconds"
    reboot_timeout: 60
  when: reboot
  become: true

- name: Shutdown
  community.general.shutdown:
    delay: 60
  when: shutdown
  become: true
