- name: DNF autoremove
  ansible.builtin.dnf:
    autoremove: true
  become: true

- name: Flatpak autoremove
  ansible.builtin.command:
    cmd: flatpak remove --unused --noninteractive --assumeyes
  changed_when: "'app/' in flatpak_autoremove_result.stdout"
  register: flatpak_autoremove_result

- name: Reboot
  ansible.builtin.command:
    cmd: shutdown -r +1 "Rebooting in 60 seconds"
  become: true
  changed_when: true
  when: reboot

- name: Shutdown
  ansible.builtin.command:
    cmd: shutdown +1 "Shutting down in 60 seconds"
  become: true
  changed_when: true
  when: shutdown
