- name: Download FiraMono nerd font
  ansible.builtin.get_url:
    dest: /tmp/firamono.zip
    mode: '0644'
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraMono.zip
  when: font
  register: down_font

- name: Make fonts dir
  ansible.builtin.file:
    mode: '0755'
    path: /usr/share/fonts
    state: directory
  become: true

- name: Make firamono dir
  ansible.builtin.file:
    mode: '0755'
    path: /usr/share/fonts/firamono
    state: directory
  become: true

- name: Unzip font
  ansible.builtin.unarchive:
    dest: /usr/share/fonts/firamono
    src: /tmp/firamono.zip
  become: true
  when: down_font is not skipped

- name: Font remove extra files
  ansible.builtin.file:
    path: "/usr/share/fonts/firamono/{{ item }}"
    state: absent
  with_items:
    - LICENSE.txt
    - readme.md
  become: true
  when: down_font is not skipped

- name: Delete font zip
  ansible.builtin.file:
    path: /tmp/firamono.zip
    state: absent

- name: Refresh font cache
  ansible.builtin.shell:
    cmd: fc-cache -fv
  when: down_font is not skipped

- name: Set Fira Font
  ansible.builtin.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/interface/document-font-name", value: "'FuraMono Nerd Font 11'" }
    - { key: "/org/gnome/desktop/interface/font-name", value: "'FuraMono Nerd Font 10'" }
    - { key: "/org/gnome/desktop/interface/monospace-font-name", value: "'FuraMono Nerd Font 11'" }
