- name: Create keybinding locations
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/',
            '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

- name: Nautilus hotkey
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Super>e'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'nautilus'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'Nautilus'" }

- name: Alacritty hotkey
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding", value: "'<Primary><Alt>t'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command", value: "'/home/{{ ansible_user_id }}/.cargo/bin/alacritty'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name", value: "'Alacritty'" }

- name: Right alt switching
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['lv3:ralt_switch']"

- name: Fix alt-tabbing
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward", value: "['<Shift><Super>Tab']"}
    - { key: "/org/gnome/desktop/wm/keybindings/switch-applications", value: "['<Super>Tab']"}
    - { key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward", value: "['<Shift><Alt>Tab']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-windows", value: "['<Alt>Tab']" }
    - { key: "/org/gnome/shell/window-switcher/current-workspace-only", value: "false" }

- name: Maximize hoykey
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/maximize"
    value: "['<Super>Up']"

- name: Printscreen hotkeys
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip", value: "['Print']" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot", value: "['<Shift>Print']" }

- name: Speed up key repeat delay and speed
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/peripherals/keyboard/delay", value: "uint32 300" }
    - { key: "/org/gnome/desktop/peripherals/keyboard/repeat-interval", value: "uint32 20" }
