- name: Configure font
  ansible.builtin.include_tasks:
    file: font.yml

- name: Configure hardware
  ansible.builtin.include_tasks:
    file: hardware.yml

- name: Configure input
  ansible.builtin.include_tasks:
    file: input.yml

- name: Configure shell
  ansible.builtin.include_tasks:
    file: shell.yml

- name: Configure UI
  ansible.builtin.include_tasks:
    file: ui.yml

- name: Install dotfiles
  ansible.builtin.include_tasks:
    file: dotfiles.yml
