- name: Correct theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"

- name: Show battery percentage
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: Set night light settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled", value: "true" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic", value: "false" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from", value: "20" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to", value: "5" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature", value: "1700" }

- name: Show week number and week day
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/calendar/show-weekdate", value: "true" }
    - { key: "/org/gnome/desktop/interface/clock-show-weekday", value: "true" }

- name: Prefer dark theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: Change background
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/background/picture-uri-dark", value: "'file:///usr/share/backgrounds/gnome/blobs-d.svg'" }
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:///usr/share/backgrounds/gnome/blobs-l.svg'" }
