- name: Show battery percentage
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: Show week number and week day
  ansible.builtin.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/calendar/show-weekdate", value: "true" }
    - { key: "/org/gnome/desktop/interface/clock-show-weekday", value: "true" }

- name: Set night light settings
  ansible.builtin.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled", value: "true" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from", value: "21.5" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to", value: "6" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature", value: "1700" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic", value: "false" }

- name: Correct theme
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"
