- name: Remove extras
  ansible.builtin.package:
    name:
      - anaconda
      - anaconda-install-env-deps
      - anaconda-live
      - baobab
      - fpaste
      - gnome-browser-connector
      - gnome-calendar
      - gnome-classic-session-xsession
      - gnome-clocks
      - gnome-connections
      - gnome-contacts
      - gnome-help
      - gnome-maps
      - gnome-photos
      - gnome-remote-desktop
      - gnome-shell-extension-background-logo
      - gnome-tour
      - gnome-weather
      - kdump-anaconda-addon
      - mediawriter
      - rhythmbox
      - snapshot
      - totem
      - yelp
    state: absent
  become: true

- name: DNF parallel downloads
  ansible.builtin.lineinfile:
    dest: /etc/dnf/dnf.conf
    line: max_parallel_downloads=20
  become: true

- name: DNF update
  ansible.builtin.package:
    name: "*"
    state: latest
    update_only: true
  become: true

- name: Flatpak update
  ansible.builtin.command:
    cmd: flatpak update --noninteractive --assumeyes
  changed_when: "'app/' in flatpak_update_result.stdout"
  register: flatpak_update_result
