- name: DNF parallel downloads
  ansible.builtin.lineinfile:
    dest: /etc/dnf/dnf.conf
    line: max_parallel_downloads=10
  become: true

- name: DNF update
  ansible.builtin.package:
    name: "*"
    state: latest
  become: true

- name: Flatpak update
  ansible.builtin.shell:
    cmd: flatpak update --noninteractive --assumeyes
  become: true

# Remove to get to more basic state
- name: Remove
  ansible.builtin.package:
    name:
      - cheese
      - gnome-boxes
      - gnome-calendar
      - gnome-clocks
      - gnome-connections
      - gnome-contacts
      - gnome-help
      - gnome-maps
      - gnome-photos
      - gnome-terminal
      - gnome-text-editor
      - gnome-tour
      - gnome-weather
      - mediawriter
      - mediawriter
      - rhythmbox
      - totem
      - yelp
    state: absent
  become: true
